### ISSUE TITLE
Bloat VS Babel 5

### ISSUE THREAD

**Issue by developit** [frostney/babel-preset-es2015-loose-rollup#1]
It would be nice if this preset excluded a few transforms that bloat filesize:
- `babel-plugin-transform-es2015-function-name`
- `babel-plugin-transform-es2015-typeof-symbol`

... see: https://github.com/Popmotion/babel-preset-es2015-subset-loose

**Comment by frostney** [comment]
I completely agree. I wish there was a way to optionally exclude/include those through `.babelrc` which I feel would be a better long-term solution.
For now, I'm going to publish a new version without these transforms.

**Comment by developit** [comment]
@frostney - so last night I actually put together a solution for this after looking at your module. Check it out: https://github.com/developit/modify-babel-preset

``` js
var modify = require('modify-babel-preset');

module.exports = modify('es2015', {
    'transform-es2015-typeof-symbol': false,
    'transform-es2015-function-name': false
});
```

Would love to hear any feedback you might have on it.

**Comment by frostney** [comment]
@developit This looks really good. :+1:  I think I'm going to change my module to use your library in one of the next versions
